"""add name to users table

Revision ID: 23f4273a2757
Revises: 12d0d32c47c5
Create Date: 2026-07-29 00:52:42.026299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23f4273a2757'
down_revision: Union[str, Sequence[str], None] = '12d0d32c47c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        "users",
        sa.Column("name", sa.String(length=100), nullable=False)
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
